# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rank.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_h5(object):
    def setupUi(self, h5):
        h5.setObjectName("h5")
        h5.resize(1400, 700)
        h5.setStyleSheet("QDialog#h5{\n"
"    \n"
"    border-image: url(:/newPrefix/backgroung.jpg);\n"
"}")
        self.label = QtWidgets.QLabel(h5)
        self.label.setGeometry(QtCore.QRect(640, 110, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("border-image: url(:/newPrefix/white.jpg);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(h5)
        self.label_2.setGeometry(QtCore.QRect(440, 210, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-image: url(:/newPrefix/white.jpg);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(h5)
        self.label_3.setGeometry(QtCore.QRect(640, 210, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border-image: url(:/newPrefix/white.jpg);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(h5)
        self.label_4.setGeometry(QtCore.QRect(840, 210, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border-image: url(:/newPrefix/white.jpg);")
        self.label_4.setObjectName("label_4")
        self.textBrowser = QtWidgets.QTextBrowser(h5)
        self.textBrowser.setGeometry(QtCore.QRect(440, 300, 90, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(h5)
        self.textBrowser_2.setGeometry(QtCore.QRect(640, 300, 90, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(h5)
        self.textBrowser_3.setGeometry(QtCore.QRect(840, 300, 150, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.textBrowser_3.setFont(font)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(h5)
        self.textBrowser_4.setGeometry(QtCore.QRect(440, 430, 90, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.textBrowser_4.setFont(font)
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(h5)
        self.textBrowser_5.setGeometry(QtCore.QRect(640, 430, 90, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.textBrowser_5.setFont(font)
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser_6 = QtWidgets.QTextBrowser(h5)
        self.textBrowser_6.setGeometry(QtCore.QRect(840, 430, 150, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.textBrowser_6.setFont(font)
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.textBrowser_7 = QtWidgets.QTextBrowser(h5)
        self.textBrowser_7.setGeometry(QtCore.QRect(440, 570, 90, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.textBrowser_7.setFont(font)
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.textBrowser_8 = QtWidgets.QTextBrowser(h5)
        self.textBrowser_8.setGeometry(QtCore.QRect(640, 570, 90, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.textBrowser_8.setFont(font)
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.textBrowser_9 = QtWidgets.QTextBrowser(h5)
        self.textBrowser_9.setGeometry(QtCore.QRect(840, 570, 150, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.textBrowser_9.setFont(font)
        self.textBrowser_9.setObjectName("textBrowser_9")

        self.retranslateUi(h5)
        QtCore.QMetaObject.connectSlotsByName(h5)

    def retranslateUi(self, h5):
        _translate = QtCore.QCoreApplication.translate
        h5.setWindowTitle(_translate("h5", "Dialog"))
        self.label.setText(_translate("h5", "排行榜"))
        self.label_2.setText(_translate("h5", "ID"))
        self.label_3.setText(_translate("h5", "积分"))
        self.label_4.setText(_translate("h5", "昵称"))
import aaa_rc
